version: '3.8'

services:
  data-collector-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-collector-service-local
    ports:
      - "8083:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-wa-kafka:9092}
    networks:
      - wa-local-network

networks:
  data-collector-local-network:
    driver: bridge
  wa-local-network:
    name: wa-local-network
    driver: bridge