version: '3.8'

services:
  data-collector-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-collector-service
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    networks:
      - data-collector-network
    restart: unless-stopped

networks:
  data-collector-network:
    driver: bridge
