spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: health-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.wa.data.collector.service.model.HealthRawData
        spring.json.type.mapping: healthRaw:org.wa.data.collector.service.model.HealthRawData
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: healthRaw:org.wa.data.collector.service.model.HealthRawData

health:
  topics:
    raw: health.raw.google
    validated: health.validated
    dlq: health.dlq
  constraints:
    heart-rate:
      min: 30
      max: 220
    steps:
      min: 0
      max: 100000
    sleep:
      min: 0.0
      max: 16.0

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG